// Code generated by protoc-gen-go. DO NOT EDIT.
// source: seq.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0df69c63ddc0f76, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Arg struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Arg) Reset()         { *m = Arg{} }
func (m *Arg) String() string { return proto.CompactTextString(m) }
func (*Arg) ProtoMessage()    {}
func (*Arg) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0df69c63ddc0f76, []int{1}
}

func (m *Arg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arg.Unmarshal(m, b)
}
func (m *Arg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arg.Marshal(b, m, deterministic)
}
func (m *Arg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arg.Merge(m, src)
}
func (m *Arg) XXX_Size() int {
	return xxx_messageInfo_Arg.Size(m)
}
func (m *Arg) XXX_DiscardUnknown() {
	xxx_messageInfo_Arg.DiscardUnknown(m)
}

var xxx_messageInfo_Arg proto.InternalMessageInfo

func (m *Arg) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Arg) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SeqId struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeqId) Reset()         { *m = SeqId{} }
func (m *SeqId) String() string { return proto.CompactTextString(m) }
func (*SeqId) ProtoMessage()    {}
func (*SeqId) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0df69c63ddc0f76, []int{2}
}

func (m *SeqId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeqId.Unmarshal(m, b)
}
func (m *SeqId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeqId.Marshal(b, m, deterministic)
}
func (m *SeqId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeqId.Merge(m, src)
}
func (m *SeqId) XXX_Size() int {
	return xxx_messageInfo_SeqId.Size(m)
}
func (m *SeqId) XXX_DiscardUnknown() {
	xxx_messageInfo_SeqId.DiscardUnknown(m)
}

var xxx_messageInfo_SeqId proto.InternalMessageInfo

func (m *SeqId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Info struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Batch                int64    `protobuf:"varint,2,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0df69c63ddc0f76, []int{3}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Info) GetBatch() int64 {
	if m != nil {
		return m.Batch
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Arg)(nil), "Arg")
	proto.RegisterType((*SeqId)(nil), "SeqId")
	proto.RegisterType((*Info)(nil), "Info")
}

func init() { proto.RegisterFile("seq.proto", fileDescriptor_b0df69c63ddc0f76) }

var fileDescriptor_b0df69c63ddc0f76 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4e, 0x2d, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x54, 0xd2,
	0xe7, 0x62, 0x76, 0x2c, 0x4a, 0x17, 0x12, 0xe2, 0x62, 0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x93, 0xf3, 0x4b, 0xf3, 0x4a, 0x24,
	0x98, 0xc0, 0x82, 0x10, 0x8e, 0x92, 0x38, 0x17, 0x6b, 0x70, 0x6a, 0xa1, 0x67, 0x8a, 0x10, 0x1f,
	0x17, 0x53, 0x66, 0x0a, 0x54, 0x03, 0x53, 0x66, 0x8a, 0x92, 0x01, 0x17, 0x8b, 0x67, 0x5e, 0x5a,
	0x3e, 0x2e, 0xa3, 0x92, 0x12, 0x4b, 0x92, 0x33, 0x60, 0x46, 0x81, 0x39, 0x46, 0xf1, 0x5c, 0xcc,
	0xc1, 0xa9, 0x85, 0x42, 0x62, 0x5c, 0x2c, 0x01, 0x99, 0x79, 0xe9, 0x42, 0x6c, 0x7a, 0x60, 0x27,
	0x49, 0x41, 0x69, 0x21, 0x21, 0x2e, 0x26, 0xcf, 0x14, 0x21, 0x16, 0x3d, 0xc7, 0xa2, 0x74, 0x29,
	0x36, 0x3d, 0x88, 0xa5, 0xc2, 0x5c, 0xcc, 0x9e, 0x29, 0xc5, 0x68, 0x82, 0xe2, 0x5c, 0x6c, 0xce,
	0x45, 0xa9, 0x89, 0x25, 0xa9, 0x42, 0xac, 0x7a, 0x20, 0x27, 0xc0, 0x4c, 0x48, 0x62, 0x03, 0x7b,
	0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x00, 0x36, 0x1d, 0xf9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SeqClient is the client API for Seq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SeqClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Id(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*SeqId, error)
	Ids(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*SeqId, error)
	Create(ctx context.Context, in *Info, opts ...grpc.CallOption) (*Empty, error)
}

type seqClient struct {
	cc *grpc.ClientConn
}

func NewSeqClient(cc *grpc.ClientConn) SeqClient {
	return &seqClient{cc}
}

func (c *seqClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Seq/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seqClient) Id(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*SeqId, error) {
	out := new(SeqId)
	err := c.cc.Invoke(ctx, "/Seq/Id", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seqClient) Ids(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*SeqId, error) {
	out := new(SeqId)
	err := c.cc.Invoke(ctx, "/Seq/Ids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seqClient) Create(ctx context.Context, in *Info, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Seq/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeqServer is the server API for Seq service.
type SeqServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	Id(context.Context, *Arg) (*SeqId, error)
	Ids(context.Context, *Arg) (*SeqId, error)
	Create(context.Context, *Info) (*Empty, error)
}

func RegisterSeqServer(s *grpc.Server, srv SeqServer) {
	s.RegisterService(&_Seq_serviceDesc, srv)
}

func _Seq_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeqServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Seq/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeqServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seq_Id_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeqServer).Id(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Seq/Id",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeqServer).Id(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seq_Ids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeqServer).Ids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Seq/Ids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeqServer).Ids(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seq_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Info)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeqServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Seq/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeqServer).Create(ctx, req.(*Info))
	}
	return interceptor(ctx, in, info, handler)
}

var _Seq_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Seq",
	HandlerType: (*SeqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Seq_Ping_Handler,
		},
		{
			MethodName: "Id",
			Handler:    _Seq_Id_Handler,
		},
		{
			MethodName: "Ids",
			Handler:    _Seq_Ids_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Seq_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seq.proto",
}
