{
 "title": "jvm",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"} / jvm_memory_bytes_max{area=\"heap\"} * 100",
     "legendFormat": "heap"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\"} / jvm_memory_bytes_max{area=\"nonheap\"} * 100",
     "legendFormat": "nonheap"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "NonHeap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "current" },
    { "expr": "jvm_threads_daemon", "legendFormat": "daemon" },
    { "expr": "jvm_threads_peak", "legendFormat": "peak" },
    { "expr": "jvm_threads_deadlocked", "legendFormat": "deadlocked" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad",
     "legendFormat": "system cpu"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad",
     "legendFormat": "process cpu"
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gc collection $rate rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count[$rate])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC time $rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 10, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum[$rate])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "gc collection $rate increase",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count[$rate])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}