{
 "title": "kafka_producer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "broker",
    "query": "label_values(incoming_byte_rate, broker)"
   },
   { "name": "job", "query": "logic,admin" },
   {
    "name": "topic",
    "query": "label_values(batch_size_bucket, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request & Response 5m rate",
   "type": "graph",
   "description": "發送訊息與響應頻率",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "request_rate{broker=\"$broker\",job=\"$job\", key=\"5m\"}",
     "legendFormat": "request"
    },
    {
     "expr": "response_rate{broker=\"$broker\",job=\"$job\", key=\"5m\"}",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Request latency in ms",
   "type": "graph",
   "description": "發送訊息平均延遲時間分佈點",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "request_latency_in_ms_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "Request & Response 5m increase",
   "type": "graph",
   "description": "發送訊息與響應次數的累加值差異",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(request_rate{broker=\"$broker\",job=\"$job\", key=\"count\"}[5m])",
     "legendFormat": "request"
    },
    {
     "expr": "increase(response_rate{broker=\"$broker\",job=\"$job\", key=\"count\"}[5m])",
     "legendFormat": "response"
    }
   ]
  },
  { "title": "Record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Record send 5m rate for topic",
   "type": "graph",
   "description": "每秒發送多少訊息到某topic",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "record_send_rate{topic=\"$topic\", job=\"$job\", key=\"5m\"}",
     "legendFormat": "5m"
    }
   ]
  },
  {
   "title": "Records per request for topic",
   "type": "graph",
   "description": "每個request發送的訊息數量大小分佈點",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "records_per_request_bucket{topic=\"$topic\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "Record send 5m increase for topic",
   "type": "graph",
   "description": "發送多少訊息到某topic\b累加值的差異",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(record_send_rate{topic=\"$topic\", job=\"$job\", key=\"count\"}[5m])",
     "legendFormat": "5m"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Bytes/second read 5m rate off broker",
   "type": "graph",
   "description": "每秒從所有broker接收的平均傳入字節數\n\n如發送訊息後的response",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "incoming_byte_rate{broker=\"$broker\", job=\"$job\", key=\"5m\"}",
     "legendFormat": "logic"
    }
   ]
  },
  {
   "title": "Request bytes off broker",
   "type": "graph",
   "description": "發送訊息的request大小分佈點 \n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "request_size_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "bytes sent per partition per request for topics",
   "type": "graph",
   "description": "每個請求對於partition發送的bytes大小分佈點",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "batch_size_bucket{topic=\"$topic\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "Bytes/second written 5m rate off broker",
   "type": "graph",
   "description": "每秒從所有broker發送的平均傳入字節數\n\n如發送訊息",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "outgoing_byte_rate{broker=\"$broker\", job=\"$job\", key=\"5m\"}",
     "legendFormat": "logic"
    }
   ]
  },
  {
   "title": "Response bytes off broker",
   "type": "graph",
   "description": "發送訊息後response大小分佈點\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "response_size_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  }
 ]
}