{
 "title": "kafka_consumer(job)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "broker",
    "query": "label_values(incoming_byte_rate, broker)"
   },
   {
    "name": "topic",
    "query": "label_values(batch_size_bucket, topic)"
   },
   { "name": "job", "query": "job,admin" },
   {
    "name": "consumer",
    "query": "label_values(kafka_burrow_consumer_status, group)"
   }
  ]
 },
 "panels": [
  { "title": "Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumer partition status",
   "type": "table",
   "description": "消費者群組負責消費的各partition狀態\n\n各狀態如下\n1 :  找不到消費者群組\n2 :  ok\n3 :  lag中\n4:  消費群組(不適用partition)內有5 ~ 7號的狀態\n5:  消費者很久沒有提交offset\n6:  消費者已提交offset但卻沒有增加(partition error)\n7:  消費者提交offset 比Broker ofset 還小 (非趨勢遞增)\n\n\n\nhttps://github.com/linkedin/Burrow/wiki/Consumer-Lag-Evaluation-Rules\n\nhttps://github.com/linkedin/Burrow/wiki/http-request-consumer-group-status#response",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_burrow_consumer_partition_status",
     "legendFormat": "{{group}}_{{topic}}_{{partition}}"
    },
    { "expr": "kafka_burrow_consumer_status", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Consumer partition current lag",
   "type": "table",
   "description": "消費者群組消費的各partition 當前 offsets lag狀況",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "kafka_burrow_consumer_partition_lag{topic=\"$topic\", group=\"$consumer\"}",
     "legendFormat": "{{topic}}_{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer partition lag for $consumer",
   "type": "graph",
   "description": "消費者群組消費的各partition offsets lag狀況",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_consumer_partition_lag{group=\"$consumer\"}",
     "legendFormat": "{{topic}}_{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer total lag for $consumer",
   "type": "graph",
   "description": "消費者群組 totla offsets lag狀況",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_consumer_total_lag{group=\"$consumer\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Consumer total current lag",
   "type": "table",
   "description": "消費者群組 當前 totla offsets lag狀況",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "kafka_burrow_consumer_total_lag",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Topic partition offset rate for $topic topic",
   "type": "graph",
   "description": "各topic下partition offsets增長速率",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_burrow_topic_partition_offset{topic=\"$topic\"}[1m])",
     "legendFormat": "{{topic}}_{{partition}}_1m"
    },
    {
     "expr": "rate(kafka_burrow_topic_partition_offset{topic=\"$topic\"}[5m])",
     "legendFormat": "{{topic}}_{{partition}}_5m"
    },
    {
     "expr": "rate(kafka_burrow_topic_partition_offset{topic=\"$topic\"}[15m])",
     "legendFormat": "{{topic}}_{{partition}}_15m"
    }
   ]
  },
  {
   "title": "Consumer partition offset rate for $consumer",
   "type": "graph",
   "description": "消費者群組 消費各partition offsets速率\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_burrow_consumer_partition_current_offset{group=\"$consumer\"}[1m])",
     "legendFormat": "{{topic}}_{{partition}}_1m"
    },
    {
     "expr": "rate(kafka_burrow_consumer_partition_current_offset{group=\"$consumer\"}[5m])",
     "legendFormat": "{{topic}}_{{partition}}_5m"
    },
    {
     "expr": "rate(kafka_burrow_consumer_partition_current_offset{group=\"$consumer\"}[15m])",
     "legendFormat": "{{topic}}_{{partition}}_15m"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Fetch request rate for $job",
   "type": "graph",
   "description": "Fetch API Request",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "request_rate{broker=\"$broker\",job=\"$job\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Fetch response rate for $job",
   "type": "graph",
   "description": "Fetch API Response 頻率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "response_rate{broker=\"$broker\",job=\"$job\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": " Fetch Request latency in ms",
   "type": "graph",
   "description": "Fetch API 平均延遲時間分佈點",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "request_latency_in_ms_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "Record",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer batch size for $job",
     "type": "graph",
     "description": "每次消費的訊息筆數分佈點",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_batch_size_bucket{job=\"job\", le=~\"0.*\"}",
       "legendFormat": "{{le}}%"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes/second read rate off broker for $job",
     "type": "graph",
     "description": "每秒從所有broker接收的平均傳入字節數\n\n如發送訊息後的response",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "incoming_byte_rate{broker=\"$broker\", job=\"$job\"}",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Bytes/second writte rate off broker for $job",
     "type": "graph",
     "description": "每秒從所有broker發送的平均傳入字節數\n\n如發送訊息",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "outgoing_byte_rate{broker=\"$broker\", job=\"$job\"}",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Request bytes off broker for $job",
     "type": "graph",
     "description": "發送訊息的request大小分佈點 \n",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "request_size_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
       "legendFormat": "{{le}}%"
      }
     ]
    },
    {
     "title": "Response bytes off broker for $job",
     "type": "graph",
     "description": "發送訊息後response大小分佈點\n",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "response_size_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
       "legendFormat": "{{le}}%"
      }
     ]
    }
   ]
  }
 ]
}