{
 "title": "kafka_broker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "label_values(kafka_server_BrokerTopicMetrics_MeanRate, topic)"
   },
   {
    "name": "request",
    "query": "Produce,FetchConsumer,FetchFollower,Fetch"
   }
  ]
 },
 "panels": [
  { "title": "Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error partitions count",
   "type": "table",
   "description": "Offline partitions count: 不能寫與讀的分區數量，不可大於0\n\nUnder replicated partitions: cluster中副本處於同步失敗或失效狀態的分區數，UnderReplicatedPartitions的值持續大於0時，意味著集群中有Broker處於異常狀態",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\"}",
     "legendFormat": "offline partitions count"
    },
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\"}",
     "legendFormat": "under replicated partitions"
    }
   ]
  },
  {
   "title": "Partitions count",
   "type": "table",
   "description": "Leader partitions count:  某broter分區leader總數，其中有50個是內建topic __consumer_offsets持有",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"LeaderCount\"}",
     "legendFormat": "leader partitions count"
    },
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\"}",
     "legendFormat": "partitions count"
    }
   ]
  },
  {
   "title": "Leader election count",
   "type": "graph",
   "description": "Leader選舉次數",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_ControllerStats_Count{name=\"LeaderElectionRateAndTimeMs\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "IO thread usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "100 - kafka_network_SocketServer_Value{name=\"NetworkProcessorAvgIdlePercent\"} * 100",
     "legendFormat": "processor"
    },
    {
     "expr": "100 - (kafka_server_KafkaRequestHandlerPool_MeanRate * 100)",
     "legendFormat": "network"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "singlestat",
   "description": "一個Cluster一定要有一個存活負責處理所有請求\n如果==0代表Cluster broker沒有選舉成功",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\"}"
    }
   ]
  },
  {
   "title": "\"$topic\" topic total bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_log_Log_Value{name=\"Size\", topic=\"$topic\"})",
     "legendFormat": "$topic"
    }
   ]
  },
  {
   "title": "ISR 5m rate",
   "type": "graph",
   "description": "ISR執行速率，最好都是0，不要過度頻繁變動會影響效能",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_FiveMinuteRate{name=\"IsrExpandsPerSec\"}",
     "legendFormat": "expands"
    },
    {
     "expr": "kafka_server_ReplicaManager_FiveMinuteRate{name=\"IsrShrinksPerSec\"}",
     "legendFormat": "shrinks"
    }
   ]
  },
  {
   "title": "ISR count",
   "type": "graph",
   "description": "ISR執行速率，最好都是0，不要過度頻繁變動會影響效能",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Count{name=\"IsrExpandsPerSec\"}",
     "legendFormat": "expands"
    },
    {
     "expr": "kafka_server_ReplicaManager_Count{name=\"IsrShrinksPerSec\"}",
     "legendFormat": "shrinks"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Bytes output rate for $topic topic",
   "type": "graph",
   "description": "kafka某topic 輸出bytes的速率\u001c",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"BytesOutPerSec\",topic=\"$topic\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "kafka_server_BrokerTopicMetrics_FiveMinuteRate{name=\"BytesOutPerSec\",topic=\"$topic\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "kafka_server_BrokerTopicMetrics_FifteenMinuteRate{name=\"BytesOutPerSec\",topic=\"$topic\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"BytesOutPerSec\",topic=\"$topic\"}",
     "legendFormat": "meam"
    }
   ]
  },
  {
   "title": "Bytes input rate for $topic topic",
   "type": "graph",
   "description": "kafka某topic 輸入bytes的速率\u001c",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"BytesInPerSec\",topic=\"$topic\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "kafka_server_BrokerTopicMetrics_FiveMinuteRate{name=\"BytesInPerSec\",topic=\"$topic\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "kafka_server_BrokerTopicMetrics_FifteenMinuteRate{name=\"BytesInPerSec\",topic=\"$topic\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"BytesInPerSec\",topic=\"$topic\"}",
     "legendFormat": "meam"
    }
   ]
  },
  {
   "title": "Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message input rate for $topic topic",
     "type": "graph",
     "description": "topic接收訊息的速率",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"MessagesInPerSec\",topic=\"$topic\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FiveMinuteRate{name=\"MessagesInPerSec\",topic=\"$topic\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FifteenMinuteRate{name=\"MessagesInPerSec\",topic=\"$topic\"}",
       "legendFormat": "15m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"MessagesInPerSec\",topic=\"$topic\"}",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "Fetch request rate for $topic topic",
     "type": "graph",
     "description": "Fetch Request速率",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"TotalFetchRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FiveMinuteRate{name=\"TotalFetchRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FifteenMinuteRate{name=\"TotalFetchRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "15m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"TotalFetchRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "Produce request rate for $topic topic ",
     "type": "graph",
     "description": "Produce Request速率",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"TotalProduceRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FiveMinuteRate{name=\"TotalProduceRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FifteenMinuteRate{name=\"TotalProduceRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "15m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"TotalProduceRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "Failed fetch request for $topic topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"FailedFetchRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FiveMinuteRate{name=\"FailedFetchRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FifteenMinuteRate{name=\"FailedFetchRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "15m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"FailedFetchRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "Failed produce request for $topic topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"FailedProduceRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FiveMinuteRate{name=\"FailedProduceRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_FifteenMinuteRate{name=\"FailedProduceRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "15m"
      },
      {
       "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"FailedProduceRequestsPerSec\", topic=\"$topic\"}",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "$request Request total time\t",
     "type": "graph",
     "description": "Request請求總時間",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_999thPercentile{name=\"TotalTimeMs\",request=\"$request\"}",
       "legendFormat": "99.9%"
      },
      {
       "expr": "kafka_network_RequestMetrics_99thPercentile{name=\"TotalTimeMs\",request=\"$request\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{name=\"TotalTimeMs\",request=\"$request\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "kafka_network_RequestMetrics_75thPercentile{name=\"TotalTimeMs\",request=\"Produce\"}",
       "legendFormat": "75%"
      },
      {
       "expr": "kafka_network_RequestMetrics_50thPercentile{name=\"TotalTimeMs\",request=\"Produce\"}",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  }
 ]
}