{
 "title": "kafka_producer(logic)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "broker",
    "query": "label_values(incoming_byte_rate, broker)"
   },
   { "name": "job", "query": "logic,admin" },
   {
    "name": "topic",
    "query": "label_values(batch_size_bucket, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request  rate for $job",
     "type": "graph",
     "description": "發送訊息",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "request_rate{broker=\"$broker\",job=\"$job\"}",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Request latency in ms for $job",
     "type": "graph",
     "description": "發送訊息平均延遲時間分佈點",
     "gridPos": { "h": 7, "w": 8, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "request_latency_in_ms_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
       "legendFormat": "{{le}}%"
      }
     ]
    },
    {
     "title": "Response rate for $job",
     "type": "graph",
     "description": "響應頻率",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "response_rate{broker=\"$broker\",job=\"$job\"}",
       "legendFormat": "{{key}}"
      }
     ]
    }
   ]
  },
  { "title": "Record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Record send rate for $topic topic",
   "type": "graph",
   "description": "每秒發送多少訊息到某topic",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "record_send_rate{topic=\"$topic\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Records per request for $topic topic",
   "type": "graph",
   "description": "每個request發送的訊息數量大小分佈點",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "records_per_request_bucket{topic=\"$topic\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Bytes/second written rate off broker for $job",
   "type": "graph",
   "description": "每秒從所有broker發送的平均傳入字節數\n\n如發送訊息",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "outgoing_byte_rate{broker=\"$broker\", job=\"$job\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Request bytes off broker for $job",
   "type": "graph",
   "description": "發送訊息的request大小分佈點 \n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "request_size_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "bytes sent per partition per request for $topic topic",
   "type": "graph",
   "description": "每個請求對於partition發送的bytes大小分佈點",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "batch_size_bucket{topic=\"$topic\",le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "Bytes/second read rate off broker for $job",
   "type": "graph",
   "description": "每秒從所有broker接收的平均傳入字節數\n\n如發送訊息後的response",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "incoming_byte_rate{broker=\"$broker\", job=\"$job\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Response bytes off broker for $job",
   "type": "graph",
   "description": "發送訊息後response大小分佈點\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "response_size_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  }
 ]
}