# database config
database:
  host: 127.0.0.1
  port: 3306
  database: alakazam
  user: root
  password: root
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  # 最大連線總數
  active: 100
  # 最大保留的閒置連線數
  idle: 10
  # 空閒連線多久(秒)沒做事就close
  idleTimeout: 2m
  slave:
    - slave1
  slave1:
    port: 3306

# redis config
redis:
  # redis host
  addr: :6379
  # pool內最大連線總數
  maxConns: 50
  # 最大保留的閒置連線數
  minIdleConns: 30
  # 建立連線超時多久(秒)後放棄
  dialTimeout: 5s
  # read多久(秒)沒回覆則放棄
  readTimeout: 2s
  # write多久(秒)沒回覆則放棄
  writeTimeout: 2s
  # 空閒連線多久(秒)沒做事就close
  idleTimeout: 5m

# kafka config
kafka:
  topic: "push-topic"
  brokers:
    - 127.0.0.1:9092

# http server for front config
http:
  debug: true
  addr: :3111
  readTimeout: 1s
  writeTimeout: 1s
  cors:
    origins:
      - '*'
    headers:
      - Origin
      - Content-Type
      - Keep-Alive
      - User-Agent
      - Authorization

# http server for admin config
admin:
  debug: true
  addr: :3112
  readTimeout: 1s
  writeTimeout: 1s

# grpc server config
grpcServer:
  addr: :3119

# 三方應用接口 config
api:
  host: http://127.0.0.1:3005
  # 最大連接數量
  maxConns: 30
  # 最大空閒連接數
  maxIdleConns: 10
  # 單一連線最多閒置多久
  idleConnTimeout: 2m