grpc:
  server:
    addr: :3120

# redis server
redis:
  # redis host
  addr: :6379
  # redis password
  password: ""
  # pool內最大連線總數
  maxConns: 8
  # 最大保留的閒置連線數
  minIdleConns: 4
  # 建立連線超時多久(秒)後放棄
  dialTimeout: 1s
  # read多久(秒)沒回覆則放棄
  readTimeout: 1s
  # write多久(秒)沒回覆則放棄
  writeTimeout: 1s
  # 空閒連線多久(秒)沒做事就close
  idleTimeout: 5m

database:
  host: 127.0.0.1
  port: 3306
  database: alakazam
  user: root
  password: root
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  # 最大連線總數
  active: 8
  # 最大保留的閒置連線數
  idle: 4
  # 空閒連線多久(秒)沒做事就close
  idleTimeout: 2m
  slave:
    host: 127.0.0.1
    port: 3306
    user: root
    password: root
    active: 8
    idle: 4
    idleTimeout: 2m

metrics:
  addr: :3034

log:
  # 開啟debug模式只會紀錄Info Level以上的log
  # 使用DPanic level時會Panic
  debug: false
  # 是否關閉log的輸出檔案代碼位置
  disableCaller: true
  # 是否關閉Warn Level(不包含)以上的stack trace message
  disableStacktrace: true
  # Error Level(包含) 以上的log是否單獨輸出
  # 不跟Info Level(包含) 以下的log輸出在同一個位置
  errorAloneOutput: false
  # log採樣基數
  sampling:
    # 當前Sync log數量大於此數字就會開始採樣
    initial: 100
    # 採樣機率
    thereafter: 10