{
 "title": "kafka_consumer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "broker",
    "query": "label_values(incoming_byte_rate, broker)"
   },
   {
    "name": "topic",
    "query": "label_values(batch_size_bucket, topic)"
   },
   { "name": "job", "query": "job,admin" }
  ]
 },
 "panels": [
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fetch Request & Response 5m rate",
   "type": "graph",
   "description": "Fetch API Request與Response 頻率",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "request_rate{broker=\"$broker\",job=\"$job\", key=\"5m\"}",
     "legendFormat": "request"
    },
    {
     "expr": "response_rate{broker=\"$broker\",job=\"$job\", key=\"5m\"}",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": " Fetch Request latency in ms",
   "type": "graph",
   "description": "Fetch API 平均延遲時間分佈點",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "request_latency_in_ms_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "Fetch Request & Response 5m increase",
   "type": "graph",
   "description": "Fetch API Request與Response累加差異值",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(request_rate{broker=\"$broker\",job=\"$job\", key=\"count\"}[5m])",
     "legendFormat": "request"
    },
    {
     "expr": "increase(response_rate{broker=\"$broker\",job=\"$job\", key=\"count\"}[5m])",
     "legendFormat": "response"
    }
   ]
  },
  { "title": "Record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Consumer batch size",
   "type": "graph",
   "description": "每次消費的訊息筆數分佈點",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumer_batch_size_bucket{job=\"job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Bytes/second read 5m rate off broker",
   "type": "graph",
   "description": "每秒從所有broker接收的平均傳入字節數\n\n如發送訊息後的response",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "incoming_byte_rate{broker=\"$broker\", job=\"$job\", key=\"5m\"}",
     "legendFormat": "logic"
    }
   ]
  },
  {
   "title": "Request bytes off broker",
   "type": "graph",
   "description": "發送訊息的request大小分佈點 \n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "request_size_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  },
  {
   "title": "Bytes/second written 5m rate off broker",
   "type": "graph",
   "description": "每秒從所有broker發送的平均傳入字節數\n\n如發送訊息",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "outgoing_byte_rate{broker=\"$broker\", job=\"$job\", key=\"5m\"}",
     "legendFormat": "logic"
    }
   ]
  },
  {
   "title": "Response bytes off broker",
   "type": "graph",
   "description": "發送訊息後response大小分佈點\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "response_size_bucket{broker=\"$broker\", job=\"$job\", le=~\"0.*\"}",
     "legendFormat": "{{le}}%"
    }
   ]
  }
 ]
}