{
 "title": "kafka_broker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "label_values(kafka_server_BrokerTopicMetrics_MeanRate, topic)"
   },
   {
    "name": "consumer_group_num",
    "query": "query_result(kafka_coordinator_group_GroupMetadataManager_Value{name=\"NumGroupsStable\"}) "
   },
   {
    "name": "rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "request",
    "query": "Produce,FetchConsumer,FetchFollower,Fetch"
   }
  ]
 },
 "panels": [
  { "title": "Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error partitions count",
   "type": "bargauge",
   "description": "Offline partitions count: 不能寫與讀的分區數量，不可大於0\n\nUnder replicated partitions: cluster中副本處於同步失敗或失效狀態的分區數，UnderReplicatedPartitions的值持續大於0時，意味著集群中有Broker處於異常狀態",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\"}",
     "legendFormat": "offline partitions count"
    },
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\"}",
     "legendFormat": "under replicated partitions"
    }
   ]
  },
  {
   "title": "Partitions count",
   "type": "bargauge",
   "description": "Leader partitions count:  某broter分區leader總數，其中有50個是內建topic __consumer_offsets持有",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"LeaderCount\"}",
     "legendFormat": "leader partitions count"
    },
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\"}",
     "legendFormat": "partitions count"
    }
   ]
  },
  {
   "title": "Leader election count",
   "type": "graph",
   "description": "Leader選舉次數",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_ControllerStats_Count{name=\"LeaderElectionRateAndTimeMs\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "ISR",
   "type": "graph",
   "description": "ISR執行速率，最好都是0，不要過度頻繁變動會影響效能",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_MeanRate{name=\"IsrExpandsPerSec\"}",
     "legendFormat": "expand"
    },
    {
     "expr": "kafka_server_ReplicaManager_MeanRate{name=\"IsrShrinksPerSec\"}",
     "legendFormat": "shrink"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "singlestat",
   "description": "一個Cluster一定要有一個存活負責處理所有請求\n如果==0代表Cluster broker沒有選舉成功",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\"}"
    }
   ]
  },
  {
   "title": "\"$topic\" topic total bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_log_Log_Value{name=\"Size\", topic=\"$topic\"})",
     "legendFormat": "$topic"
    }
   ]
  },
  {
   "title": "IO thread usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - kafka_network_SocketServer_Value{name=\"NetworkProcessorAvgIdlePercent\"} * 100",
     "legendFormat": "processor"
    },
    {
     "expr": "100 - (kafka_server_KafkaRequestHandlerPool_MeanRate * 100)",
     "legendFormat": "network"
    }
   ]
  },
  {
   "title": "Replica Lag Message",
   "type": "graph",
   "description": "follower落後leader replica的最大的消息數量\n",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaFetcherManager_Value{name=\"MaxLag\"}",
     "legendFormat": "max lag"
    },
    { "expr": "kafka_server_FetcherLagMetrics" }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Bytes input/output $rate rate",
   "type": "graph",
   "description": "kafka某topic 進出bytes的速率\u001c",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\",topic=\"$topic\"}[$rate])",
     "legendFormat": "bytes in rate"
    },
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\",topic=\"$topic\"}[$rate])/$consumer_group_num",
     "legendFormat": "bytes out rate"
    },
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\",topic=\"$topic\"}[$rate])",
     "legendFormat": "bytes all out rate"
    }
   ]
  },
  {
   "title": "Bytes input/output $rate increase",
   "type": "graph",
   "description": "kafka某topic 進出bytes的累加差值",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\",topic=\"$topic\"}[$rate])",
     "legendFormat": "bytes in rate"
    },
    {
     "expr": "increase(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\",topic=\"$topic\"}[$rate])/$consumer_group_num",
     "legendFormat": "bytes out rate"
    },
    {
     "expr": "increase(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\",topic=\"$topic\"}[$rate])",
     "legendFormat": "bytes all out rate"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Request $rate rate",
   "type": "graph",
   "description": "Request速率",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalFetchRequestsPerSec\", topic=\"$topic\"}[$rate])",
     "legendFormat": "fetch rate"
    },
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalProduceRequestsPerSec\",topic=\"$topic\"}[$rate])",
     "legendFormat": "produce rate"
    },
    {
     "expr": "increase(kafka_server_BrokerTopicMetrics_Count{name=\"TotalProduceRequestsPerSec\",topic=\"$topic\"}[$rate])",
     "legendFormat": "produce increase"
    }
   ]
  },
  {
   "title": "Message input $rate rate",
   "type": "graph",
   "description": "topic接收訊息的速率",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "increase(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",topic=\"$topic\"}[$rate])",
     "legendFormat": "message increase"
    },
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",topic=\"$topic\"}[$rate])",
     "legendFormat": "message rate"
    }
   ]
  },
  {
   "title": "Failed request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_Count{name=\"FailedFetchRequestsPerSec\", topic=\"$topic\"}",
     "legendFormat": "fetch"
    },
    {
     "expr": "kafka_server_BrokerTopicMetrics_Count{name=\"FailedProduceRequestsPerSec\", topic=\"$topic\"}",
     "legendFormat": "produce"
    }
   ]
  },
  {
   "title": "$request Request total time\t",
   "type": "graph",
   "description": "Request請求總時間",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_999thPercentile{name=\"TotalTimeMs\",request=\"$request\"}",
     "legendFormat": "99.9%"
    },
    {
     "expr": "kafka_network_RequestMetrics_99thPercentile{name=\"TotalTimeMs\",request=\"$request\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "kafka_network_RequestMetrics_95thPercentile{name=\"TotalTimeMs\",request=\"$request\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "kafka_network_RequestMetrics_75thPercentile{name=\"TotalTimeMs\",request=\"Produce\"}",
     "legendFormat": "75%"
    },
    {
     "expr": "kafka_network_RequestMetrics_50thPercentile{name=\"TotalTimeMs\",request=\"Produce\"}",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}