{
 "title": "node",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU核心數",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100"
    }
   ]
  },
  {
   "title": "當前打開的文件描述符",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "node_filefd_allocated" }
   ]
  },
  {
   "title": "當前打開的文件描述符比例",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "(node_filefd_allocated/node_filefd_maximum)*100"
    }
   ]
  },
  {
   "title": "內存總量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "CPU平均負載",
   "type": "graph",
   "description": "理想值小於1.0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" }
   ]
  },
  {
   "title": "內存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "內存總量" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "已用"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "cached" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "可用" }
   ]
  },
  {
   "title": "CPU使用率，磁盤每秒的I / O操作耗費時間（％）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "内核操作"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "用户進程"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1m])) by (instance)",
     "legendFormat": "空閒"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "TCP連接狀況",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "ESTABLISHED 之間 CLOSE-WAIT" },
    { "expr": "node_sockstat_TCP_tw", "legendFormat": "待關閉的TCP連接數" },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens[1m])",
     "legendFormat": "CLOSED 到 SYN-SENT 平均連接數(5m)"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens[1m])",
     "legendFormat": "LISTEN 到 SYN-RCVD 平均連接數(5m)"
    },
    { "expr": "node_sockstat_TCP_alloc", "legendFormat": "已分配" },
    { "expr": "node_sockstat_TCP_inuse", "legendFormat": "使用" }
   ]
  }
 ]
}